<?php

use Carbon\Traits\Timestamp;
use Illuminate\Database\Seeder;

class EngineersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('engineers')->insert([
            [
                'last_name' => '竈門',
                'first_name' => '炭治郎',
                'last_name_furigana' => 'カマド',
                'first_name_furigana' => 'タンジロウ',
                'gender' => '男',
                'birth_date' => '1980-07-22',
                'email' => 'tanjiro@gmai.com',
                'tel' => '090-5444-5555',
                'address' => '福岡県博多区銀天町1-876',
                'postal_code' => '000-0000',
                'closest_station' => '博多駅',
                'educational_background' => '鱗滝道場卒',
                'comment' => 'やさしい',
                'employment_status_id' => 3,
                'in_house_status_id' => 1,
                'engineer_skill_id' => 1,
                'human_skill_id' => 1,
            ],
            [
                'last_name' => '竈門',
                'first_name' => '禰豆子',
                'last_name_furigana' => 'カマド',
                'first_name_furigana' => 'ネズコ',
                'gender' => '鬼',
                'birth_date' => '1986-12-28',
                'email' => 'nezuko@gmai.com',
                'tel' => '090-5444-5566',
                'address' => '福岡県博多区銀天町1-876',
                'postal_code' => '000-0000',
                'closest_station' => '博多駅',
                'educational_background' => '鱗滝道場卒',
                'comment' => '強い',
                'employment_status_id' => 2,
                'in_house_status_id' => 2,
                'engineer_skill_id' => 1,
                'human_skill_id' => 1,
            ],
            [
                'last_name' => '我妻',
                'first_name' => '善逸',
                'last_name_furigana' => 'アガツマ',
                'first_name_furigana' => 'ゼンイツ',
                'gender' => '男',
                'birth_date' => '1984-09-03',
                'email' => 'zenithu@gmai.com',
                'tel' => '090-5444-4466',
                'address' => '東京都足立区青井5-0989',
                'postal_code' => '000-0000',
                'closest_station' => '東京駅',
                'educational_background' => '桑島道場卒',
                'comment' => 'やる時はやる',
                'employment_status_id' => 1,
                'in_house_status_id' => 2,
                'engineer_skill_id' => 3,
                'human_skill_id' => 1,
            ],
            [
                'last_name' => '嘴平',
                'first_name' => '伊之助',
                'last_name_furigana' => 'ヒシビラ',
                'first_name_furigana' => 'イノスケ',
                'gender' => '男',
                'birth_date' => '1980-04-22',
                'email' => 'inosuke@gmai.com',
                'tel' => '090-5343-5566',
                'address' => '佐賀県唐津市朝日町950-0',
                'postal_code' => '000-0000',
                'closest_station' => '佐賀駅',
                'educational_background' => '山で修行した',
                'comment' => '気合いと根性',
                'employment_status_id' => 2,
                'in_house_status_id' => 2,
                'engineer_skill_id' => 1,
                'human_skill_id' => 3,

            ],
            [
                'last_name' => '栗花落',
                'first_name' => 'カナヲ',
                'last_name_furigana' => 'ツユリ',
                'first_name_furigana' => 'カナヲ',
                'gender' => '女',
                'birth_date' => '1990-05-19',
                'email' => 'kanawo@gmai.com',
                'tel' => '090-8444-5566',
                'address' => '京都府京都市上京区内藤町471',
                'postal_code' => '000-0000',
                'closest_station' => '京都駅',
                'educational_background' => '胡蝶道場卒',
                'comment' => '最後の方に喋り出した',
                'employment_status_id' => 4,
                'in_house_status_id' => 2,
                'engineer_skill_id' => 1,
                'human_skill_id' => 1,
            ],
            [
                'last_name' => '不死川',
                'first_name' => '玄弥',
                'last_name_furigana' => 'シナズガワ',
                'first_name_furigana' => 'ゲンヤ',
                'gender' => '男',
                'birth_date' => '1990-01-07',
                'email' => 'genya@gmai.com',
                'tel' => '090-9876-5566',
                'address' => '長崎県西海市大島町13-22',
                'postal_code' => '000-0000',
                'closest_station' => '長崎駅',
                'educational_background' => '悲鳴嶼道場卒',
                'comment' => '半分鬼',
                'employment_status_id' => 2,
                'in_house_status_id' => 2,
                'engineer_skill_id' => 1,
                'human_skill_id' => 1,
            ],
            [
                'last_name' => '冨岡',
                'first_name' => '義勇',
                'last_name_furigana' => 'トミオカ',
                'first_name_furigana' => 'ギユウ',
                'gender' => '男',
                'birth_date' => '1976-02-08',
                'email' => 'giyu@gmai.com',
                'tel' => '090-5444-8767',
                'address' => '福岡県久留米市野中町453-8',
                'postal_code' => '000-0000',
                'closest_station' => '博多駅',
                'educational_background' => '鱗滝道場卒',
                'comment' => '十一の型をあみだした',
                'employment_status_id' => 2,
                'in_house_status_id' => 2,
                'engineer_skill_id' => 1,
                'human_skill_id' => 3,
            ],

        ]);
    }
}
